const lang = {
  en: {
    search: "search",
    gptSearchPlaceholder: "What would you like to watch today ?",
    signUp: "Sign Up",
    signIn: "Sign In",
    signOut: "Sign Out",
    already_registered: " Already Registered",
    now: "Now",
    gpt: "GPT",
    home: "Home",
    emailPlaceholder: "email address",
    namePlaceholder: "Full Name",
    passwordPlaceholder: "password",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upComing: "UpComing",
    newNetFlix: "New to NetFlix ",
    alreadyRegis: "Already Registered",
    moreLikeThis: "More Like This",
    trailersAndMore: "Trailers and more",
    myList: "My List",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: " आज आप क्या देखना चाहेंगे?",
    signUp: "साइन अप",
    signIn: "साइन इन",
    signOut: "साइन आउट",
    already_registered: " पहले साइन अप किया",
    now: "अभी",
    gpt: "जीपीटी",
    home: "होम पेज",
    emailPlaceholder: "ईमेल पता",
    namePlaceholder: "पूरा नाम",
    passwordPlaceholder: "पासवर्ड",
    nowPlaying: "अभी चल रहा है",
    popular: "पॉपुलर",
    topRated: "टॉप रेटेड",
    upComing: "आगामी",
    newNetFlix: "नेटफ्लिक्स पर नया",
    alreadyRegis: "पहले साइन अप किया",
    moreLikeThis: "समान फिल्में",
    trailersAndMore: "ट्रेलर और बहुत कुछ",
    myList: "मेरी सूची",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    signUp: "Registrarse",
    signIn: "Iniciar Sesión",
    signOut: "Cerrar Sesión",
    already_registered: "Ya estás registrado",
    now: "Ahora",
    gpt: "GPT",
    home: "Home",
    emailPlaceholder: "dirección de correo electrónico",
    namePlaceholder: "Nombre Completo",
    passwordPlaceholder: "contraseña",
    nowPlaying: "Ahora jugando",
    popular: "Popular",
    topRated: "Mejor valorado",
    upComing: "Próximos",
    newNetFlix: "Nuevos en NetFlix",
    alreadyRegis: "Ya estás registrado",
    moreLikeThis: "más como esto",
    trailersAndMore: "Remolques y más",
    myList: "mi lista",
  },
};

export default lang;
